export enum ActionType {
  COMMENT = 'COMMENT',
  LIKE = 'LIKE',
  DONATE = 'DONATE',
  PROJECT_TIME_OUT = 'PROJECT_TIME_OUT',
  PROJECT_GOAL_ACHIEVED = 'PROJECT_GOAL_ACHIEVED',
  NEW_PROJECT = 'NEW_PROJECT',
  GET_WATCHING_USERS = 'GET_WATCHING_USERS'
}
