version: '3'
services:
  gateway:
    image: "mihailts/hypecrafter-gateway"
    env_file:
      - .env
  backend:
    depends_on:
      - gateway
    image: "mihailts/hypecrafter-backend"
    env_file:
      - .env
  frontend:
    stdin_open: true
    image: "mihailts/hypecrafter-frontend"
  nginx:
    depends_on:
      - frontend
      - gateway
      - backend
    restart: always
    image: "mihailts/hypecrafter-nginx"
    ports:
      - '80:80'
