export enum ProjectKeys {
  NAME = 'name',
  DESCRIPTION = 'description',
  CATEGORY = 'category',
  CONTENT = 'content',
  GOAL = 'goal',
  REGION = 'region',
  START_DATE = 'startDate',
  FINISH_DATE = 'finishDate',
  TEAM = 'team',
  IMAGE_URL = 'imageUrl',
  VIDEO_URL = 'videoUrl',
  PROJECT_TAGS = 'projectTags',
  DONATORS_PRIVILEGES = 'donatorsPrivileges',
  INSTAGRAM = 'instagramUrl',
  FACEBOOK = 'facebookUrl',
  DRIBBLE = 'dribbleUrl',
  PINTEREST = 'pinterestUrl',
  BEHANCE = 'behanceUrl'
}
